CREATE TABLE [dbo].[Days]
(
	DAYNUMBER INT NOT NULL PRIMARY KEY,
	DAYOFWEEKNUMBER INT NOT NULL,
	DAYOFWEEKNAME CHAR NOT NULL,
	MONTHNUMBER INT NOT NULL

	CONSTRAINT MKEY FOREIGN KEY(MONTHNUMBER)
	REFERENCES [dbo].[Months](MONTHNUMBER)
)
