CREATE TABLE [dbo].[Months]
(
	  MONTHNUMBER INT NOT NULL PRIMARY KEY,
      MONTHSNAME CHAR NOT NULL,
      NUMBEROFDAYS INT NOT NULL,
	  YEARNUMBER INT NOT NULL

	  CONSTRAINT YFKEY FOREIGN KEY(YEARNUMBER)
	  REFERENCES [dbo].[Years](YEARNUMBER)
)
